// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrkbusyjbstspebzvcdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxya2J1c3lqYnN0c3BlYnp2Y2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyMjcyMTcsImV4cCI6MjEwMDgwMzIxN30.3KiPlb0AwFv9nttmTUxzgTyLxKlzTg_BiNG-3hmpAvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});